// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comm.proto

#ifndef PROTOBUF_comm_2eproto__INCLUDED
#define PROTOBUF_comm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace GNET {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_comm_2eproto();
void protobuf_AssignDesc_comm_2eproto();
void protobuf_ShutdownFile_comm_2eproto();

class MSyncOp;
class MSync;

// ===================================================================

class MSyncOp : public ::google::protobuf::Message {
 public:
  MSyncOp();
  virtual ~MSyncOp();

  MSyncOp(const MSyncOp& from);

  inline MSyncOp& operator=(const MSyncOp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSyncOp& default_instance();

  void Swap(MSyncOp* other);

  // implements Message ----------------------------------------------

  MSyncOp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSyncOp& from);
  void MergeFrom(const MSyncOp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 add = 1;
  inline bool has_add() const;
  inline void clear_add();
  static const int kAddFieldNumber = 1;
  inline ::google::protobuf::int32 add() const;
  inline void set_add(::google::protobuf::int32 value);

  // optional int32 del = 2;
  inline bool has_del() const;
  inline void clear_del();
  static const int kDelFieldNumber = 2;
  inline ::google::protobuf::int32 del() const;
  inline void set_del(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GNET.MSyncOp)
 private:
  inline void set_has_add();
  inline void clear_has_add();
  inline void set_has_del();
  inline void clear_has_del();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 add_;
  ::google::protobuf::int32 del_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_comm_2eproto();
  friend void protobuf_AssignDesc_comm_2eproto();
  friend void protobuf_ShutdownFile_comm_2eproto();

  void InitAsDefaultInstance();
  static MSyncOp* default_instance_;
};
// -------------------------------------------------------------------

class MSync : public ::google::protobuf::Message {
 public:
  MSync();
  virtual ~MSync();

  MSync(const MSync& from);

  inline MSync& operator=(const MSync& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSync& default_instance();

  void Swap(MSync* other);

  // implements Message ----------------------------------------------

  MSync* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSync& from);
  void MergeFrom(const MSync& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int64 id() const;
  inline void set_id(::google::protobuf::int64 value);

  // required .GNET.MSyncOp op = 2;
  inline bool has_op() const;
  inline void clear_op();
  static const int kOpFieldNumber = 2;
  inline const ::GNET::MSyncOp& op() const;
  inline ::GNET::MSyncOp* mutable_op();
  inline ::GNET::MSyncOp* release_op();
  inline void set_allocated_op(::GNET::MSyncOp* op);

  // @@protoc_insertion_point(class_scope:GNET.MSync)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_op();
  inline void clear_has_op();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 id_;
  ::GNET::MSyncOp* op_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_comm_2eproto();
  friend void protobuf_AssignDesc_comm_2eproto();
  friend void protobuf_ShutdownFile_comm_2eproto();

  void InitAsDefaultInstance();
  static MSync* default_instance_;
};
// ===================================================================


// ===================================================================

// MSyncOp

// optional int32 add = 1;
inline bool MSyncOp::has_add() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSyncOp::set_has_add() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSyncOp::clear_has_add() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSyncOp::clear_add() {
  add_ = 0;
  clear_has_add();
}
inline ::google::protobuf::int32 MSyncOp::add() const {
  return add_;
}
inline void MSyncOp::set_add(::google::protobuf::int32 value) {
  set_has_add();
  add_ = value;
}

// optional int32 del = 2;
inline bool MSyncOp::has_del() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSyncOp::set_has_del() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSyncOp::clear_has_del() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSyncOp::clear_del() {
  del_ = 0;
  clear_has_del();
}
inline ::google::protobuf::int32 MSyncOp::del() const {
  return del_;
}
inline void MSyncOp::set_del(::google::protobuf::int32 value) {
  set_has_del();
  del_ = value;
}

// -------------------------------------------------------------------

// MSync

// required int64 id = 1;
inline bool MSync::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MSync::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MSync::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MSync::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::int64 MSync::id() const {
  return id_;
}
inline void MSync::set_id(::google::protobuf::int64 value) {
  set_has_id();
  id_ = value;
}

// required .GNET.MSyncOp op = 2;
inline bool MSync::has_op() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MSync::set_has_op() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MSync::clear_has_op() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MSync::clear_op() {
  if (op_ != NULL) op_->::GNET::MSyncOp::Clear();
  clear_has_op();
}
inline const ::GNET::MSyncOp& MSync::op() const {
  return op_ != NULL ? *op_ : *default_instance_->op_;
}
inline ::GNET::MSyncOp* MSync::mutable_op() {
  set_has_op();
  if (op_ == NULL) op_ = new ::GNET::MSyncOp;
  return op_;
}
inline ::GNET::MSyncOp* MSync::release_op() {
  clear_has_op();
  ::GNET::MSyncOp* temp = op_;
  op_ = NULL;
  return temp;
}
inline void MSync::set_allocated_op(::GNET::MSyncOp* op) {
  delete op_;
  op_ = op;
  if (op) {
    set_has_op();
  } else {
    clear_has_op();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GNET

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_comm_2eproto__INCLUDED
