// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s2g.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "s2g.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace GNET {

namespace {

const ::google::protobuf::Descriptor* MS2G_REG_REQ_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MS2G_REG_REQ_reflection_ = NULL;
const ::google::protobuf::Descriptor* MG2S_REG_RES_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MG2S_REG_RES_reflection_ = NULL;
const ::google::protobuf::Descriptor* MG2S_SYNC_REQ_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MG2S_SYNC_REQ_reflection_ = NULL;
const ::google::protobuf::Descriptor* MS2G_SYNC_RES_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MS2G_SYNC_RES_reflection_ = NULL;
const ::google::protobuf::Descriptor* MS2G_FWD_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MS2G_FWD_reflection_ = NULL;
const ::google::protobuf::Descriptor* MG2S_FWD_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MG2S_FWD_reflection_ = NULL;
const ::google::protobuf::Descriptor* MS2G_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MS2G_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* EN_CMD_S2G_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_s2g_2eproto() {
  protobuf_AddDesc_s2g_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "s2g.proto");
  GOOGLE_CHECK(file != NULL);
  MS2G_REG_REQ_descriptor_ = file->message_type(0);
  static const int MS2G_REG_REQ_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_REG_REQ, id_),
  };
  MS2G_REG_REQ_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MS2G_REG_REQ_descriptor_,
      MS2G_REG_REQ::default_instance_,
      MS2G_REG_REQ_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_REG_REQ, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_REG_REQ, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MS2G_REG_REQ));
  MG2S_REG_RES_descriptor_ = file->message_type(1);
  static const int MG2S_REG_RES_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_REG_RES, result_),
  };
  MG2S_REG_RES_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MG2S_REG_RES_descriptor_,
      MG2S_REG_RES::default_instance_,
      MG2S_REG_RES_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_REG_RES, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_REG_RES, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MG2S_REG_RES));
  MG2S_SYNC_REQ_descriptor_ = file->message_type(2);
  static const int MG2S_SYNC_REQ_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_SYNC_REQ, seq_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_SYNC_REQ, sync_),
  };
  MG2S_SYNC_REQ_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MG2S_SYNC_REQ_descriptor_,
      MG2S_SYNC_REQ::default_instance_,
      MG2S_SYNC_REQ_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_SYNC_REQ, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_SYNC_REQ, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MG2S_SYNC_REQ));
  MS2G_SYNC_RES_descriptor_ = file->message_type(3);
  static const int MS2G_SYNC_RES_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_SYNC_RES, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_SYNC_RES, seq_),
  };
  MS2G_SYNC_RES_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MS2G_SYNC_RES_descriptor_,
      MS2G_SYNC_RES::default_instance_,
      MS2G_SYNC_RES_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_SYNC_RES, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_SYNC_RES, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MS2G_SYNC_RES));
  MS2G_FWD_descriptor_ = file->message_type(4);
  static const int MS2G_FWD_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_FWD, to_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_FWD, data_),
  };
  MS2G_FWD_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MS2G_FWD_descriptor_,
      MS2G_FWD::default_instance_,
      MS2G_FWD_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_FWD, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G_FWD, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MS2G_FWD));
  MG2S_FWD_descriptor_ = file->message_type(5);
  static const int MG2S_FWD_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_FWD, from_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_FWD, data_),
  };
  MG2S_FWD_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MG2S_FWD_descriptor_,
      MG2S_FWD::default_instance_,
      MG2S_FWD_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_FWD, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MG2S_FWD, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MG2S_FWD));
  MS2G_descriptor_ = file->message_type(6);
  static const int MS2G_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, cmd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, timestamp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, ms2g_reg_req_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, mg2s_reg_res_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, mg2s_sync_req_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, ms2g_sync_res_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, ms2g_fwd_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, mg2s_fwd_),
  };
  MS2G_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MS2G_descriptor_,
      MS2G::default_instance_,
      MS2G_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MS2G, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MS2G));
  EN_CMD_S2G_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_s2g_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MS2G_REG_REQ_descriptor_, &MS2G_REG_REQ::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MG2S_REG_RES_descriptor_, &MG2S_REG_RES::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MG2S_SYNC_REQ_descriptor_, &MG2S_SYNC_REQ::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MS2G_SYNC_RES_descriptor_, &MS2G_SYNC_RES::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MS2G_FWD_descriptor_, &MS2G_FWD::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MG2S_FWD_descriptor_, &MG2S_FWD::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MS2G_descriptor_, &MS2G::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_s2g_2eproto() {
  delete MS2G_REG_REQ::default_instance_;
  delete MS2G_REG_REQ_reflection_;
  delete MG2S_REG_RES::default_instance_;
  delete MG2S_REG_RES_reflection_;
  delete MG2S_SYNC_REQ::default_instance_;
  delete MG2S_SYNC_REQ_reflection_;
  delete MS2G_SYNC_RES::default_instance_;
  delete MS2G_SYNC_RES_reflection_;
  delete MS2G_FWD::default_instance_;
  delete MS2G_FWD_reflection_;
  delete MG2S_FWD::default_instance_;
  delete MG2S_FWD_reflection_;
  delete MS2G::default_instance_;
  delete MS2G_reflection_;
}

void protobuf_AddDesc_s2g_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::GNET::protobuf_AddDesc_comm_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\ts2g.proto\022\004GNET\032\ncomm.proto\"\032\n\014MS2G_RE"
    "G_REQ\022\n\n\002id\030\001 \002(\003\"\036\n\014MG2S_REG_RES\022\016\n\006res"
    "ult\030\001 \002(\005\"7\n\rMG2S_SYNC_REQ\022\013\n\003seq\030\001 \002(\005\022"
    "\031\n\004sync\030\002 \003(\0132\013.GNET.MSync\",\n\rMS2G_SYNC_"
    "RES\022\016\n\006result\030\001 \002(\005\022\013\n\003seq\030\002 \002(\005\"$\n\010MS2G"
    "_FWD\022\n\n\002to\030\001 \002(\005\022\014\n\004data\030\002 \002(\014\"&\n\010MG2S_F"
    "WD\022\014\n\004from\030\001 \002(\005\022\014\n\004data\030\002 \002(\014\"\250\002\n\004MS2G\022"
    "\035\n\003cmd\030\001 \002(\0162\020.GNET.EN_CMD_S2G\022\021\n\ttimest"
    "amp\030\002 \001(\005\022(\n\014ms2g_reg_req\030e \001(\0132\022.GNET.M"
    "S2G_REG_REQ\022(\n\014mg2s_reg_res\030f \001(\0132\022.GNET"
    ".MG2S_REG_RES\022*\n\rmg2s_sync_req\030g \001(\0132\023.G"
    "NET.MG2S_SYNC_REQ\022*\n\rms2g_sync_res\030h \001(\013"
    "2\023.GNET.MS2G_SYNC_RES\022 \n\010ms2g_fwd\030i \001(\0132"
    "\016.GNET.MS2G_FWD\022 \n\010mg2s_fwd\030j \001(\0132\016.GNET"
    ".MG2S_FWD*\204\001\n\nEN_CMD_S2G\022\023\n\017CMD_S2G_REG_"
    "REQ\020\001\022\023\n\017CMD_G2S_REG_RES\020\002\022\024\n\020CMD_G2S_SY"
    "NC_REQ\020\003\022\024\n\020CMD_S2G_SYNC_RES\020\004\022\017\n\013CMD_G2"
    "S_FWD\020\005\022\017\n\013CMD_S2G_FWD\020\006", 704);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "s2g.proto", &protobuf_RegisterTypes);
  MS2G_REG_REQ::default_instance_ = new MS2G_REG_REQ();
  MG2S_REG_RES::default_instance_ = new MG2S_REG_RES();
  MG2S_SYNC_REQ::default_instance_ = new MG2S_SYNC_REQ();
  MS2G_SYNC_RES::default_instance_ = new MS2G_SYNC_RES();
  MS2G_FWD::default_instance_ = new MS2G_FWD();
  MG2S_FWD::default_instance_ = new MG2S_FWD();
  MS2G::default_instance_ = new MS2G();
  MS2G_REG_REQ::default_instance_->InitAsDefaultInstance();
  MG2S_REG_RES::default_instance_->InitAsDefaultInstance();
  MG2S_SYNC_REQ::default_instance_->InitAsDefaultInstance();
  MS2G_SYNC_RES::default_instance_->InitAsDefaultInstance();
  MS2G_FWD::default_instance_->InitAsDefaultInstance();
  MG2S_FWD::default_instance_->InitAsDefaultInstance();
  MS2G::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_s2g_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_s2g_2eproto {
  StaticDescriptorInitializer_s2g_2eproto() {
    protobuf_AddDesc_s2g_2eproto();
  }
} static_descriptor_initializer_s2g_2eproto_;
const ::google::protobuf::EnumDescriptor* EN_CMD_S2G_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EN_CMD_S2G_descriptor_;
}
bool EN_CMD_S2G_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int MS2G_REG_REQ::kIdFieldNumber;
#endif  // !_MSC_VER

MS2G_REG_REQ::MS2G_REG_REQ()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MS2G_REG_REQ::InitAsDefaultInstance() {
}

MS2G_REG_REQ::MS2G_REG_REQ(const MS2G_REG_REQ& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MS2G_REG_REQ::SharedCtor() {
  _cached_size_ = 0;
  id_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MS2G_REG_REQ::~MS2G_REG_REQ() {
  SharedDtor();
}

void MS2G_REG_REQ::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MS2G_REG_REQ::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MS2G_REG_REQ::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MS2G_REG_REQ_descriptor_;
}

const MS2G_REG_REQ& MS2G_REG_REQ::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_s2g_2eproto();
  return *default_instance_;
}

MS2G_REG_REQ* MS2G_REG_REQ::default_instance_ = NULL;

MS2G_REG_REQ* MS2G_REG_REQ::New() const {
  return new MS2G_REG_REQ;
}

void MS2G_REG_REQ::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = GOOGLE_LONGLONG(0);
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MS2G_REG_REQ::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MS2G_REG_REQ::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MS2G_REG_REQ::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MS2G_REG_REQ::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MS2G_REG_REQ::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MS2G_REG_REQ* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MS2G_REG_REQ*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MS2G_REG_REQ::MergeFrom(const MS2G_REG_REQ& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MS2G_REG_REQ::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MS2G_REG_REQ::CopyFrom(const MS2G_REG_REQ& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MS2G_REG_REQ::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MS2G_REG_REQ::Swap(MS2G_REG_REQ* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MS2G_REG_REQ::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MS2G_REG_REQ_descriptor_;
  metadata.reflection = MS2G_REG_REQ_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MG2S_REG_RES::kResultFieldNumber;
#endif  // !_MSC_VER

MG2S_REG_RES::MG2S_REG_RES()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MG2S_REG_RES::InitAsDefaultInstance() {
}

MG2S_REG_RES::MG2S_REG_RES(const MG2S_REG_RES& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MG2S_REG_RES::SharedCtor() {
  _cached_size_ = 0;
  result_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MG2S_REG_RES::~MG2S_REG_RES() {
  SharedDtor();
}

void MG2S_REG_RES::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MG2S_REG_RES::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MG2S_REG_RES::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MG2S_REG_RES_descriptor_;
}

const MG2S_REG_RES& MG2S_REG_RES::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_s2g_2eproto();
  return *default_instance_;
}

MG2S_REG_RES* MG2S_REG_RES::default_instance_ = NULL;

MG2S_REG_RES* MG2S_REG_RES::New() const {
  return new MG2S_REG_RES;
}

void MG2S_REG_RES::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    result_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MG2S_REG_RES::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
          set_has_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MG2S_REG_RES::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 result = 1;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MG2S_REG_RES::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 result = 1;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MG2S_REG_RES::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 result = 1;
    if (has_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->result());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MG2S_REG_RES::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MG2S_REG_RES* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MG2S_REG_RES*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MG2S_REG_RES::MergeFrom(const MG2S_REG_RES& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MG2S_REG_RES::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MG2S_REG_RES::CopyFrom(const MG2S_REG_RES& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MG2S_REG_RES::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MG2S_REG_RES::Swap(MG2S_REG_RES* other) {
  if (other != this) {
    std::swap(result_, other->result_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MG2S_REG_RES::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MG2S_REG_RES_descriptor_;
  metadata.reflection = MG2S_REG_RES_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MG2S_SYNC_REQ::kSeqFieldNumber;
const int MG2S_SYNC_REQ::kSyncFieldNumber;
#endif  // !_MSC_VER

MG2S_SYNC_REQ::MG2S_SYNC_REQ()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MG2S_SYNC_REQ::InitAsDefaultInstance() {
}

MG2S_SYNC_REQ::MG2S_SYNC_REQ(const MG2S_SYNC_REQ& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MG2S_SYNC_REQ::SharedCtor() {
  _cached_size_ = 0;
  seq_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MG2S_SYNC_REQ::~MG2S_SYNC_REQ() {
  SharedDtor();
}

void MG2S_SYNC_REQ::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MG2S_SYNC_REQ::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MG2S_SYNC_REQ::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MG2S_SYNC_REQ_descriptor_;
}

const MG2S_SYNC_REQ& MG2S_SYNC_REQ::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_s2g_2eproto();
  return *default_instance_;
}

MG2S_SYNC_REQ* MG2S_SYNC_REQ::default_instance_ = NULL;

MG2S_SYNC_REQ* MG2S_SYNC_REQ::New() const {
  return new MG2S_SYNC_REQ;
}

void MG2S_SYNC_REQ::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    seq_ = 0;
  }
  sync_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MG2S_SYNC_REQ::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 seq = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &seq_)));
          set_has_seq();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_sync;
        break;
      }

      // repeated .GNET.MSync sync = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_sync:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_sync()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_sync;
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MG2S_SYNC_REQ::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 seq = 1;
  if (has_seq()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->seq(), output);
  }

  // repeated .GNET.MSync sync = 2;
  for (int i = 0; i < this->sync_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->sync(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MG2S_SYNC_REQ::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 seq = 1;
  if (has_seq()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->seq(), target);
  }

  // repeated .GNET.MSync sync = 2;
  for (int i = 0; i < this->sync_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->sync(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MG2S_SYNC_REQ::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 seq = 1;
    if (has_seq()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->seq());
    }

  }
  // repeated .GNET.MSync sync = 2;
  total_size += 1 * this->sync_size();
  for (int i = 0; i < this->sync_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->sync(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MG2S_SYNC_REQ::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MG2S_SYNC_REQ* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MG2S_SYNC_REQ*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MG2S_SYNC_REQ::MergeFrom(const MG2S_SYNC_REQ& from) {
  GOOGLE_CHECK_NE(&from, this);
  sync_.MergeFrom(from.sync_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_seq()) {
      set_seq(from.seq());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MG2S_SYNC_REQ::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MG2S_SYNC_REQ::CopyFrom(const MG2S_SYNC_REQ& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MG2S_SYNC_REQ::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  for (int i = 0; i < sync_size(); i++) {
    if (!this->sync(i).IsInitialized()) return false;
  }
  return true;
}

void MG2S_SYNC_REQ::Swap(MG2S_SYNC_REQ* other) {
  if (other != this) {
    std::swap(seq_, other->seq_);
    sync_.Swap(&other->sync_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MG2S_SYNC_REQ::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MG2S_SYNC_REQ_descriptor_;
  metadata.reflection = MG2S_SYNC_REQ_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MS2G_SYNC_RES::kResultFieldNumber;
const int MS2G_SYNC_RES::kSeqFieldNumber;
#endif  // !_MSC_VER

MS2G_SYNC_RES::MS2G_SYNC_RES()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MS2G_SYNC_RES::InitAsDefaultInstance() {
}

MS2G_SYNC_RES::MS2G_SYNC_RES(const MS2G_SYNC_RES& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MS2G_SYNC_RES::SharedCtor() {
  _cached_size_ = 0;
  result_ = 0;
  seq_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MS2G_SYNC_RES::~MS2G_SYNC_RES() {
  SharedDtor();
}

void MS2G_SYNC_RES::SharedDtor() {
  if (this != default_instance_) {
  }
}

void MS2G_SYNC_RES::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MS2G_SYNC_RES::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MS2G_SYNC_RES_descriptor_;
}

const MS2G_SYNC_RES& MS2G_SYNC_RES::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_s2g_2eproto();
  return *default_instance_;
}

MS2G_SYNC_RES* MS2G_SYNC_RES::default_instance_ = NULL;

MS2G_SYNC_RES* MS2G_SYNC_RES::New() const {
  return new MS2G_SYNC_RES;
}

void MS2G_SYNC_RES::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    result_ = 0;
    seq_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MS2G_SYNC_RES::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 result = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
          set_has_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_seq;
        break;
      }

      // required int32 seq = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_seq:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &seq_)));
          set_has_seq();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MS2G_SYNC_RES::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 result = 1;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  // required int32 seq = 2;
  if (has_seq()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->seq(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MS2G_SYNC_RES::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 result = 1;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  // required int32 seq = 2;
  if (has_seq()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->seq(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MS2G_SYNC_RES::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 result = 1;
    if (has_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->result());
    }

    // required int32 seq = 2;
    if (has_seq()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->seq());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MS2G_SYNC_RES::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MS2G_SYNC_RES* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MS2G_SYNC_RES*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MS2G_SYNC_RES::MergeFrom(const MS2G_SYNC_RES& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
    if (from.has_seq()) {
      set_seq(from.seq());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MS2G_SYNC_RES::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MS2G_SYNC_RES::CopyFrom(const MS2G_SYNC_RES& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MS2G_SYNC_RES::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MS2G_SYNC_RES::Swap(MS2G_SYNC_RES* other) {
  if (other != this) {
    std::swap(result_, other->result_);
    std::swap(seq_, other->seq_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MS2G_SYNC_RES::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MS2G_SYNC_RES_descriptor_;
  metadata.reflection = MS2G_SYNC_RES_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MS2G_FWD::kToFieldNumber;
const int MS2G_FWD::kDataFieldNumber;
#endif  // !_MSC_VER

MS2G_FWD::MS2G_FWD()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MS2G_FWD::InitAsDefaultInstance() {
}

MS2G_FWD::MS2G_FWD(const MS2G_FWD& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MS2G_FWD::SharedCtor() {
  _cached_size_ = 0;
  to_ = 0;
  data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MS2G_FWD::~MS2G_FWD() {
  SharedDtor();
}

void MS2G_FWD::SharedDtor() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (this != default_instance_) {
  }
}

void MS2G_FWD::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MS2G_FWD::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MS2G_FWD_descriptor_;
}

const MS2G_FWD& MS2G_FWD::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_s2g_2eproto();
  return *default_instance_;
}

MS2G_FWD* MS2G_FWD::default_instance_ = NULL;

MS2G_FWD* MS2G_FWD::New() const {
  return new MS2G_FWD;
}

void MS2G_FWD::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    to_ = 0;
    if (has_data()) {
      if (data_ != &::google::protobuf::internal::kEmptyString) {
        data_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MS2G_FWD::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 to = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &to_)));
          set_has_to();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_data;
        break;
      }

      // required bytes data = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MS2G_FWD::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 to = 1;
  if (has_to()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->to(), output);
  }

  // required bytes data = 2;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MS2G_FWD::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 to = 1;
  if (has_to()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->to(), target);
  }

  // required bytes data = 2;
  if (has_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MS2G_FWD::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 to = 1;
    if (has_to()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->to());
    }

    // required bytes data = 2;
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MS2G_FWD::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MS2G_FWD* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MS2G_FWD*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MS2G_FWD::MergeFrom(const MS2G_FWD& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_to()) {
      set_to(from.to());
    }
    if (from.has_data()) {
      set_data(from.data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MS2G_FWD::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MS2G_FWD::CopyFrom(const MS2G_FWD& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MS2G_FWD::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MS2G_FWD::Swap(MS2G_FWD* other) {
  if (other != this) {
    std::swap(to_, other->to_);
    std::swap(data_, other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MS2G_FWD::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MS2G_FWD_descriptor_;
  metadata.reflection = MS2G_FWD_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MG2S_FWD::kFromFieldNumber;
const int MG2S_FWD::kDataFieldNumber;
#endif  // !_MSC_VER

MG2S_FWD::MG2S_FWD()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MG2S_FWD::InitAsDefaultInstance() {
}

MG2S_FWD::MG2S_FWD(const MG2S_FWD& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MG2S_FWD::SharedCtor() {
  _cached_size_ = 0;
  from_ = 0;
  data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MG2S_FWD::~MG2S_FWD() {
  SharedDtor();
}

void MG2S_FWD::SharedDtor() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (this != default_instance_) {
  }
}

void MG2S_FWD::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MG2S_FWD::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MG2S_FWD_descriptor_;
}

const MG2S_FWD& MG2S_FWD::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_s2g_2eproto();
  return *default_instance_;
}

MG2S_FWD* MG2S_FWD::default_instance_ = NULL;

MG2S_FWD* MG2S_FWD::New() const {
  return new MG2S_FWD;
}

void MG2S_FWD::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    from_ = 0;
    if (has_data()) {
      if (data_ != &::google::protobuf::internal::kEmptyString) {
        data_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MG2S_FWD::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 from = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &from_)));
          set_has_from();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_data;
        break;
      }

      // required bytes data = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MG2S_FWD::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 from = 1;
  if (has_from()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->from(), output);
  }

  // required bytes data = 2;
  if (has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      2, this->data(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MG2S_FWD::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 from = 1;
  if (has_from()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->from(), target);
  }

  // required bytes data = 2;
  if (has_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->data(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MG2S_FWD::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 from = 1;
    if (has_from()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->from());
    }

    // required bytes data = 2;
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->data());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MG2S_FWD::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MG2S_FWD* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MG2S_FWD*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MG2S_FWD::MergeFrom(const MG2S_FWD& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_from()) {
      set_from(from.from());
    }
    if (from.has_data()) {
      set_data(from.data());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MG2S_FWD::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MG2S_FWD::CopyFrom(const MG2S_FWD& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MG2S_FWD::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MG2S_FWD::Swap(MG2S_FWD* other) {
  if (other != this) {
    std::swap(from_, other->from_);
    std::swap(data_, other->data_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MG2S_FWD::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MG2S_FWD_descriptor_;
  metadata.reflection = MG2S_FWD_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int MS2G::kCmdFieldNumber;
const int MS2G::kTimestampFieldNumber;
const int MS2G::kMs2GRegReqFieldNumber;
const int MS2G::kMg2SRegResFieldNumber;
const int MS2G::kMg2SSyncReqFieldNumber;
const int MS2G::kMs2GSyncResFieldNumber;
const int MS2G::kMs2GFwdFieldNumber;
const int MS2G::kMg2SFwdFieldNumber;
#endif  // !_MSC_VER

MS2G::MS2G()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MS2G::InitAsDefaultInstance() {
  ms2g_reg_req_ = const_cast< ::GNET::MS2G_REG_REQ*>(&::GNET::MS2G_REG_REQ::default_instance());
  mg2s_reg_res_ = const_cast< ::GNET::MG2S_REG_RES*>(&::GNET::MG2S_REG_RES::default_instance());
  mg2s_sync_req_ = const_cast< ::GNET::MG2S_SYNC_REQ*>(&::GNET::MG2S_SYNC_REQ::default_instance());
  ms2g_sync_res_ = const_cast< ::GNET::MS2G_SYNC_RES*>(&::GNET::MS2G_SYNC_RES::default_instance());
  ms2g_fwd_ = const_cast< ::GNET::MS2G_FWD*>(&::GNET::MS2G_FWD::default_instance());
  mg2s_fwd_ = const_cast< ::GNET::MG2S_FWD*>(&::GNET::MG2S_FWD::default_instance());
}

MS2G::MS2G(const MS2G& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MS2G::SharedCtor() {
  _cached_size_ = 0;
  cmd_ = 1;
  timestamp_ = 0;
  ms2g_reg_req_ = NULL;
  mg2s_reg_res_ = NULL;
  mg2s_sync_req_ = NULL;
  ms2g_sync_res_ = NULL;
  ms2g_fwd_ = NULL;
  mg2s_fwd_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MS2G::~MS2G() {
  SharedDtor();
}

void MS2G::SharedDtor() {
  if (this != default_instance_) {
    delete ms2g_reg_req_;
    delete mg2s_reg_res_;
    delete mg2s_sync_req_;
    delete ms2g_sync_res_;
    delete ms2g_fwd_;
    delete mg2s_fwd_;
  }
}

void MS2G::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MS2G::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MS2G_descriptor_;
}

const MS2G& MS2G::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_s2g_2eproto();
  return *default_instance_;
}

MS2G* MS2G::default_instance_ = NULL;

MS2G* MS2G::New() const {
  return new MS2G;
}

void MS2G::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    cmd_ = 1;
    timestamp_ = 0;
    if (has_ms2g_reg_req()) {
      if (ms2g_reg_req_ != NULL) ms2g_reg_req_->::GNET::MS2G_REG_REQ::Clear();
    }
    if (has_mg2s_reg_res()) {
      if (mg2s_reg_res_ != NULL) mg2s_reg_res_->::GNET::MG2S_REG_RES::Clear();
    }
    if (has_mg2s_sync_req()) {
      if (mg2s_sync_req_ != NULL) mg2s_sync_req_->::GNET::MG2S_SYNC_REQ::Clear();
    }
    if (has_ms2g_sync_res()) {
      if (ms2g_sync_res_ != NULL) ms2g_sync_res_->::GNET::MS2G_SYNC_RES::Clear();
    }
    if (has_ms2g_fwd()) {
      if (ms2g_fwd_ != NULL) ms2g_fwd_->::GNET::MS2G_FWD::Clear();
    }
    if (has_mg2s_fwd()) {
      if (mg2s_fwd_ != NULL) mg2s_fwd_->::GNET::MG2S_FWD::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MS2G::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .GNET.EN_CMD_S2G cmd = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::GNET::EN_CMD_S2G_IsValid(value)) {
            set_cmd(static_cast< ::GNET::EN_CMD_S2G >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_timestamp;
        break;
      }

      // optional int32 timestamp = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &timestamp_)));
          set_has_timestamp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(810)) goto parse_ms2g_reg_req;
        break;
      }

      // optional .GNET.MS2G_REG_REQ ms2g_reg_req = 101;
      case 101: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ms2g_reg_req:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ms2g_reg_req()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(818)) goto parse_mg2s_reg_res;
        break;
      }

      // optional .GNET.MG2S_REG_RES mg2s_reg_res = 102;
      case 102: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_mg2s_reg_res:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_mg2s_reg_res()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(826)) goto parse_mg2s_sync_req;
        break;
      }

      // optional .GNET.MG2S_SYNC_REQ mg2s_sync_req = 103;
      case 103: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_mg2s_sync_req:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_mg2s_sync_req()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(834)) goto parse_ms2g_sync_res;
        break;
      }

      // optional .GNET.MS2G_SYNC_RES ms2g_sync_res = 104;
      case 104: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ms2g_sync_res:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ms2g_sync_res()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(842)) goto parse_ms2g_fwd;
        break;
      }

      // optional .GNET.MS2G_FWD ms2g_fwd = 105;
      case 105: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ms2g_fwd:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ms2g_fwd()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(850)) goto parse_mg2s_fwd;
        break;
      }

      // optional .GNET.MG2S_FWD mg2s_fwd = 106;
      case 106: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_mg2s_fwd:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_mg2s_fwd()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MS2G::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .GNET.EN_CMD_S2G cmd = 1;
  if (has_cmd()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->cmd(), output);
  }

  // optional int32 timestamp = 2;
  if (has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->timestamp(), output);
  }

  // optional .GNET.MS2G_REG_REQ ms2g_reg_req = 101;
  if (has_ms2g_reg_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      101, this->ms2g_reg_req(), output);
  }

  // optional .GNET.MG2S_REG_RES mg2s_reg_res = 102;
  if (has_mg2s_reg_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      102, this->mg2s_reg_res(), output);
  }

  // optional .GNET.MG2S_SYNC_REQ mg2s_sync_req = 103;
  if (has_mg2s_sync_req()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      103, this->mg2s_sync_req(), output);
  }

  // optional .GNET.MS2G_SYNC_RES ms2g_sync_res = 104;
  if (has_ms2g_sync_res()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      104, this->ms2g_sync_res(), output);
  }

  // optional .GNET.MS2G_FWD ms2g_fwd = 105;
  if (has_ms2g_fwd()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      105, this->ms2g_fwd(), output);
  }

  // optional .GNET.MG2S_FWD mg2s_fwd = 106;
  if (has_mg2s_fwd()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      106, this->mg2s_fwd(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MS2G::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .GNET.EN_CMD_S2G cmd = 1;
  if (has_cmd()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->cmd(), target);
  }

  // optional int32 timestamp = 2;
  if (has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->timestamp(), target);
  }

  // optional .GNET.MS2G_REG_REQ ms2g_reg_req = 101;
  if (has_ms2g_reg_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        101, this->ms2g_reg_req(), target);
  }

  // optional .GNET.MG2S_REG_RES mg2s_reg_res = 102;
  if (has_mg2s_reg_res()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        102, this->mg2s_reg_res(), target);
  }

  // optional .GNET.MG2S_SYNC_REQ mg2s_sync_req = 103;
  if (has_mg2s_sync_req()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        103, this->mg2s_sync_req(), target);
  }

  // optional .GNET.MS2G_SYNC_RES ms2g_sync_res = 104;
  if (has_ms2g_sync_res()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        104, this->ms2g_sync_res(), target);
  }

  // optional .GNET.MS2G_FWD ms2g_fwd = 105;
  if (has_ms2g_fwd()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        105, this->ms2g_fwd(), target);
  }

  // optional .GNET.MG2S_FWD mg2s_fwd = 106;
  if (has_mg2s_fwd()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        106, this->mg2s_fwd(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MS2G::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .GNET.EN_CMD_S2G cmd = 1;
    if (has_cmd()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->cmd());
    }

    // optional int32 timestamp = 2;
    if (has_timestamp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->timestamp());
    }

    // optional .GNET.MS2G_REG_REQ ms2g_reg_req = 101;
    if (has_ms2g_reg_req()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->ms2g_reg_req());
    }

    // optional .GNET.MG2S_REG_RES mg2s_reg_res = 102;
    if (has_mg2s_reg_res()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->mg2s_reg_res());
    }

    // optional .GNET.MG2S_SYNC_REQ mg2s_sync_req = 103;
    if (has_mg2s_sync_req()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->mg2s_sync_req());
    }

    // optional .GNET.MS2G_SYNC_RES ms2g_sync_res = 104;
    if (has_ms2g_sync_res()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->ms2g_sync_res());
    }

    // optional .GNET.MS2G_FWD ms2g_fwd = 105;
    if (has_ms2g_fwd()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->ms2g_fwd());
    }

    // optional .GNET.MG2S_FWD mg2s_fwd = 106;
    if (has_mg2s_fwd()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->mg2s_fwd());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MS2G::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MS2G* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MS2G*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MS2G::MergeFrom(const MS2G& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cmd()) {
      set_cmd(from.cmd());
    }
    if (from.has_timestamp()) {
      set_timestamp(from.timestamp());
    }
    if (from.has_ms2g_reg_req()) {
      mutable_ms2g_reg_req()->::GNET::MS2G_REG_REQ::MergeFrom(from.ms2g_reg_req());
    }
    if (from.has_mg2s_reg_res()) {
      mutable_mg2s_reg_res()->::GNET::MG2S_REG_RES::MergeFrom(from.mg2s_reg_res());
    }
    if (from.has_mg2s_sync_req()) {
      mutable_mg2s_sync_req()->::GNET::MG2S_SYNC_REQ::MergeFrom(from.mg2s_sync_req());
    }
    if (from.has_ms2g_sync_res()) {
      mutable_ms2g_sync_res()->::GNET::MS2G_SYNC_RES::MergeFrom(from.ms2g_sync_res());
    }
    if (from.has_ms2g_fwd()) {
      mutable_ms2g_fwd()->::GNET::MS2G_FWD::MergeFrom(from.ms2g_fwd());
    }
    if (from.has_mg2s_fwd()) {
      mutable_mg2s_fwd()->::GNET::MG2S_FWD::MergeFrom(from.mg2s_fwd());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MS2G::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MS2G::CopyFrom(const MS2G& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MS2G::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_ms2g_reg_req()) {
    if (!this->ms2g_reg_req().IsInitialized()) return false;
  }
  if (has_mg2s_reg_res()) {
    if (!this->mg2s_reg_res().IsInitialized()) return false;
  }
  if (has_mg2s_sync_req()) {
    if (!this->mg2s_sync_req().IsInitialized()) return false;
  }
  if (has_ms2g_sync_res()) {
    if (!this->ms2g_sync_res().IsInitialized()) return false;
  }
  if (has_ms2g_fwd()) {
    if (!this->ms2g_fwd().IsInitialized()) return false;
  }
  if (has_mg2s_fwd()) {
    if (!this->mg2s_fwd().IsInitialized()) return false;
  }
  return true;
}

void MS2G::Swap(MS2G* other) {
  if (other != this) {
    std::swap(cmd_, other->cmd_);
    std::swap(timestamp_, other->timestamp_);
    std::swap(ms2g_reg_req_, other->ms2g_reg_req_);
    std::swap(mg2s_reg_res_, other->mg2s_reg_res_);
    std::swap(mg2s_sync_req_, other->mg2s_sync_req_);
    std::swap(ms2g_sync_res_, other->ms2g_sync_res_);
    std::swap(ms2g_fwd_, other->ms2g_fwd_);
    std::swap(mg2s_fwd_, other->mg2s_fwd_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MS2G::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MS2G_descriptor_;
  metadata.reflection = MS2G_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GNET

// @@protoc_insertion_point(global_scope)
